import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <div className={styles.topLogo}>Hello, it’s Mayu</div>
      
      <div className={styles.top}>
        <div className={styles.imageUnset}>
          <Image src="/profile-photo.jpg" alt="profile" layout="fill" objectFit='contain' className={styles.imageProfile}/>
        </div>

        <div className={styles.name}>
          <h3 className={styles.nameTitle}>Mayu Watanabe</h3>
          <p>9 | Semptember | 1994</p>
          <p>Based in Miyagi, Japan</p>
          <p>mayuwatanabe.work@gmail.com</p>
        </div>
      </div>
      
      <main className={styles.main}>
        <div className={styles.sectionInfo}>
          <div className={styles.sectionItem}>
            <div className={styles.item}>
              <h3 className={styles.itemTitle}>Personal Values</h3>
              <p>responsibility</p>
              <p>creativity</p>
              <p>cooperation</p>
              <p>curiosity</p>
            </div>

            <div className={styles.item}>
              <h3 className={styles.itemTitle}>Languages</h3>
              <p>Japanese (native)</p>
              <p>English (intermediate)</p>
            </div>

            <div className={styles.item}>
              <h3 className={styles.itemTitle}>Skills</h3>
              <div className={styles.itemItem}>
                <h4 className={styles.itemTextBold}>Languages</h4>
                <p>html, css, javascript, php, mysql</p>
              </div>
              <div className={styles.itemItem}>
                <h4 className={styles.itemTextBold}>Tools</h4>
                <p>git, vagrant, docker, PHPUnit</p>
              </div>
              <div className={styles.itemItem}>
                <h4 className={styles.itemTextBold}>OS</h4>
                <p>windows, mac, linux</p>
              </div>
            </div>
          </div>

          <div className={styles.sectionItem}>
            <div className={styles.item}>
              <h3 className={styles.itemTitle}>Education</h3>
              <div className={styles.itemItem}>
                <h4 className={styles.itemTextBold}>Department of Business Administration,<br/>Faculty of Economics</h4>
                <p>Tohoku University</p>
                <p>2014-2019</p>
              </div>

              <div className={styles.itemItem}>
                <h4 className={styles.itemTextBold}>Department of Economics,<br/>Faculty of Social Sciences (Exchange)</h4>
                <p>University of Copenhagen</p>
                <p>2016-2017</p>
              </div>
            </div>

            <div className={styles.item}>
              <h3 className={styles.itemTitle}>Work Experience</h3>
              <h4 className={styles.itemTextBold}>Web Developer</h4>
              <p>2019-current</p>
            </div>
          </div>
        </div>
      </main>
      

      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
